import Head from "next/head";
const CosmosClient = require("@azure/cosmos").CosmosClient;
import config from "../../config";

export default function Home({ CosmosData }) {
  return (
    <>
      <Head>
        <title>Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="h-screen flex items-center justify-center bg-gray-200">
          <div className="bg-white p-8 w-[32rem]">
            <div className="flex font-500 text-sm">
              <span className="text-green-600">__</span>
              <p>THE CLOUD BLOG</p>
              <span className="text-green-600">__</span>
            </div>

            {CosmosData.map(({ id, title, content }) => (
              <div className="mb-4" key={id}>
                <h2 className="font-bold text-3xl mt-2">{title}</h2>

                <p className="mt-5">
                  Written by:
                  <a href="#" className="text-green-600">
                    {" "}
                    Anisat Ahmed
                  </a>
                </p>

                <h3 className="font-bold text-xl mt-4"> Intro </h3>
                <p className="font-light"> {content}</p>

                <button className="bg-green-600 text-white font-semibold py-2 px-5 text-sm mt-6 inline-flex items-center group">
                  <p className="pr-2"> READ MORE </p>
                  <i className="fa-solid fa-chevron-right"></i>
                </button>
                <hr className="mt-4" />
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}

Home.getInitialProps = async function () {
  const { endpoint, key, database, container } = config;

  const client = new CosmosClient({ endpoint, key });

  const databaseID = client.database(database);
  const containerID = databaseID.container(container);

  if (endpoint) {
    console.log(`Querying container:\\n${containerID}`);
    const querySpec = {
      query: "SELECT * FROM c",
    };

    const { resources: items } = await containerID.items
      .query(querySpec)
      .fetchAll();
    return { CosmosData: items };
  }
};
